algorithms:
  - name: CTD4
    hyperparameters:
      actor_lr: 1e-4
      critic_lr: 1e-3
      gamma: 0.99
      tau: 0.005
      buffer_size: 1000000
      ensemble_size: 3
      policy_noise_decay: 0.999999



  - name: DDPG
    hyperparameters:
      actor_lr: 3e-4
      critic_lr: 3e-4
      gamma: 0.99
      tau: 0.005
      buffer_size: 1000000

  - name: SAC
    hyperparameters:
      actor_lr: 3e-4
      critic_lr: 3e-4
      alpha_lr: 3e-4
      gamma: 0.99
      tau: 0.005
      buffer_size: 1000000
      log_std_bounds: [-20, 2]

  - name: TQC
    hyperparameters:
      actor_lr: 3e-4
      critic_lr: 3e-4
      alpha_lr: 3e-4
      gamma: 0.99
      tau: 0.005
      buffer_size: 1000000
      top_quantiles_to_drop: 2
      n_quantiles: 25
      log_std_bounds: [-20, 2]
      num_critics: 5

  - name: TD3
    hyperparameters:
      actor_lr: 3e-4
      critic_lr: 3e-4
      gamma: 0.99
      tau: 0.005
      buffer_size: 1000000